CREATE TABLE heapdog_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    role     VARCHAR(255),
    CONSTRAINT pk_heapdog_user PRIMARY KEY (id)
);

ALTER TABLE heapdog_user
    ADD CONSTRAINT uc_heapdog_user_email UNIQUE (email);

ALTER TABLE heapdog_user
    ADD CONSTRAINT uc_heapdog_user_username UNIQUE (username);