CREATE TABLE password_reset_otp
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by_id BIGINT,
    updated_by_id BIGINT,
    is_deleted    BOOLEAN                                 NOT NULL,
    otp           VARCHAR(255)                            NOT NULL,
    expires_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_password_reset_otp PRIMARY KEY (id)
);

ALTER TABLE password_reset_otp
    ADD CONSTRAINT uc_password_reset_otp_user UNIQUE (user_id);

ALTER TABLE password_reset_otp
    ADD CONSTRAINT FK_PASSWORD_RESET_OTP_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES heapdog_user (id);

ALTER TABLE password_reset_otp
    ADD CONSTRAINT FK_PASSWORD_RESET_OTP_ON_UPDATED_BY FOREIGN KEY (updated_by_id) REFERENCES heapdog_user (id);

ALTER TABLE password_reset_otp
    ADD CONSTRAINT FK_PASSWORD_RESET_OTP_ON_USER FOREIGN KEY (user_id) REFERENCES heapdog_user (id);